package com.heronix.repository;

import com.heronix.model.domain.ReportHistory;
import com.heronix.model.domain.ReportHistory.ReportType;
import com.heronix.model.domain.ReportHistory.ReportStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Repository for ReportHistory entities
 *
 * Provides data access methods for report history tracking.
 * Supports querying by type, status, date range, and user.
 *
 * @author Heronix Development Team
 * @version 1.0
 * @since Phase 50 - Report API Endpoints
 */
@Repository
public interface ReportHistoryRepository extends JpaRepository<ReportHistory, Long> {

    /**
     * Find all reports by type
     */
    List<ReportHistory> findByReportType(ReportType reportType);

    /**
     * Find all reports by status
     */
    List<ReportHistory> findByStatus(ReportStatus status);

    /**
     * Find all reports generated by a specific user
     */
    List<ReportHistory> findByGeneratedBy(String generatedBy);

    /**
     * Find all scheduled reports
     */
    List<ReportHistory> findByScheduledTrue();

    /**
     * Find all reports generated in a date range
     */
    List<ReportHistory> findByGeneratedAtBetween(LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Find recent reports (last N days)
     */
    @Query("SELECT r FROM ReportHistory r WHERE r.generatedAt >= :sinceDate ORDER BY r.generatedAt DESC")
    List<ReportHistory> findRecentReports(@Param("sinceDate") LocalDateTime sinceDate);

    /**
     * Find reports by type and status
     */
    List<ReportHistory> findByReportTypeAndStatus(ReportType reportType, ReportStatus status);

    /**
     * Find old reports for cleanup (older than N days and not accessed recently)
     */
    @Query("SELECT r FROM ReportHistory r WHERE r.generatedAt < :cutoffDate " +
           "AND (r.lastAccessed IS NULL OR r.lastAccessed < :cutoffDate) " +
           "AND r.status NOT IN ('PENDING', 'GENERATING')")
    List<ReportHistory> findOldReportsForCleanup(@Param("cutoffDate") LocalDateTime cutoffDate);

    /**
     * Count reports by type
     */
    long countByReportType(ReportType reportType);

    /**
     * Count reports by status
     */
    long countByStatus(ReportStatus status);

    /**
     * Delete reports older than specified date
     */
    void deleteByGeneratedAtBefore(LocalDateTime date);
}
