package com.heronix.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Compliance Report DTO
 *
 * Represents compliance status and audit information for reports.
 *
 * Features:
 * - Regulatory compliance tracking
 * - Audit trail
 * - Policy enforcement
 * - Violation detection
 * - Compliance scoring
 *
 * Standards:
 * - FERPA (Family Educational Rights and Privacy Act)
 * - GDPR (General Data Protection Regulation)
 * - HIPAA (Health Insurance Portability and Accountability Act)
 * - SOX (Sarbanes-Oxley Act)
 * - Custom policies
 *
 * @author Heronix Development Team
 * @version 1.0
 * @since Phase 75 - Report Compliance & Audit
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ComplianceReport {

    /**
     * Compliance standard enumeration
     */
    public enum ComplianceStandard {
        FERPA,          // Family Educational Rights and Privacy Act
        GDPR,           // General Data Protection Regulation
        HIPAA,          // Health Insurance Portability and Accountability Act
        SOX,            // Sarbanes-Oxley Act
        COPPA,          // Children's Online Privacy Protection Act
        CCPA,           // California Consumer Privacy Act
        PCI_DSS,        // Payment Card Industry Data Security Standard
        ISO_27001,      // Information Security Management
        CUSTOM          // Custom compliance standard
    }

    /**
     * Compliance status enumeration
     */
    public enum ComplianceStatus {
        COMPLIANT,      // Fully compliant
        PARTIAL,        // Partially compliant
        NON_COMPLIANT,  // Not compliant
        PENDING,        // Pending review
        EXEMPT,         // Exempt from compliance
        UNKNOWN         // Unknown status
    }

    /**
     * Violation severity enumeration
     */
    public enum ViolationSeverity {
        CRITICAL,       // Critical violation
        HIGH,           // High severity
        MEDIUM,         // Medium severity
        LOW,            // Low severity
        INFO            // Informational
    }

    // ============================================================
    // Basic Information
    // ============================================================

    /**
     * Compliance report ID
     */
    private Long complianceId;

    /**
     * Report ID being audited
     */
    private Long reportId;

    /**
     * Report name
     */
    private String reportName;

    /**
     * Compliance standard
     */
    private ComplianceStandard standard;

    /**
     * Compliance status
     */
    private ComplianceStatus status;

    /**
     * Generated at
     */
    private LocalDateTime generatedAt;

    /**
     * Generated by
     */
    private String generatedBy;

    /**
     * Valid from
     */
    private LocalDateTime validFrom;

    /**
     * Valid until
     */
    private LocalDateTime validUntil;

    // ============================================================
    // Compliance Score
    // ============================================================

    /**
     * Overall compliance score (0-100)
     */
    private Double complianceScore;

    /**
     * Data privacy score (0-100)
     */
    private Double dataPrivacyScore;

    /**
     * Access control score (0-100)
     */
    private Double accessControlScore;

    /**
     * Audit trail score (0-100)
     */
    private Double auditTrailScore;

    /**
     * Encryption score (0-100)
     */
    private Double encryptionScore;

    /**
     * Retention policy score (0-100)
     */
    private Double retentionPolicyScore;

    // ============================================================
    // Violations
    // ============================================================

    /**
     * Total violations
     */
    private Integer totalViolations;

    /**
     * Critical violations
     */
    private Integer criticalViolations;

    /**
     * High violations
     */
    private Integer highViolations;

    /**
     * Medium violations
     */
    private Integer mediumViolations;

    /**
     * Low violations
     */
    private Integer lowViolations;

    /**
     * Violation details
     */
    private List<ComplianceViolation> violations;

    // ============================================================
    // Policy Checks
    // ============================================================

    /**
     * Total policy checks
     */
    private Integer totalChecks;

    /**
     * Passed checks
     */
    private Integer passedChecks;

    /**
     * Failed checks
     */
    private Integer failedChecks;

    /**
     * Policy check results
     */
    private List<PolicyCheck> policyChecks;

    // ============================================================
    // Data Protection
    // ============================================================

    /**
     * Contains PII (Personally Identifiable Information)
     */
    private Boolean containsPII;

    /**
     * Contains PHI (Protected Health Information)
     */
    private Boolean containsPHI;

    /**
     * Contains financial data
     */
    private Boolean containsFinancialData;

    /**
     * Data classification level
     */
    private String dataClassification;

    /**
     * Sensitive fields identified
     */
    private List<String> sensitiveFields;

    /**
     * Encryption status
     */
    private Boolean isEncrypted;

    /**
     * Encryption method
     */
    private String encryptionMethod;

    // ============================================================
    // Access Control
    // ============================================================

    /**
     * Access controls in place
     */
    private Boolean hasAccessControls;

    /**
     * Role-based access enabled
     */
    private Boolean roleBasedAccessEnabled;

    /**
     * Authentication required
     */
    private Boolean authenticationRequired;

    /**
     * Multi-factor authentication
     */
    private Boolean mfaEnabled;

    /**
     * Unauthorized access attempts
     */
    private Integer unauthorizedAttempts;

    // ============================================================
    // Audit Trail
    // ============================================================

    /**
     * Audit logging enabled
     */
    private Boolean auditLoggingEnabled;

    /**
     * Audit records count
     */
    private Integer auditRecordsCount;

    /**
     * Audit retention days
     */
    private Integer auditRetentionDays;

    /**
     * Last audit date
     */
    private LocalDateTime lastAuditDate;

    /**
     * Audit completeness score (0-100)
     */
    private Double auditCompletenessScore;

    // ============================================================
    // Retention Policy
    // ============================================================

    /**
     * Retention policy defined
     */
    private Boolean hasRetentionPolicy;

    /**
     * Retention period (days)
     */
    private Integer retentionPeriodDays;

    /**
     * Auto-delete enabled
     */
    private Boolean autoDeleteEnabled;

    /**
     * Delete after retention
     */
    private Boolean deleteAfterRetention;

    /**
     * Records beyond retention
     */
    private Integer recordsBeyondRetention;

    // ============================================================
    // Recommendations
    // ============================================================

    /**
     * Compliance recommendations
     */
    private List<String> recommendations;

    /**
     * Remediation actions
     */
    private List<RemediationAction> remediationActions;

    /**
     * Priority actions
     */
    private List<String> priorityActions;

    // ============================================================
    // Certifications
    // ============================================================

    /**
     * Certification required
     */
    private Boolean certificationRequired;

    /**
     * Certified by
     */
    private String certifiedBy;

    /**
     * Certification date
     */
    private LocalDateTime certificationDate;

    /**
     * Certification expires
     */
    private LocalDateTime certificationExpires;

    /**
     * Next review date
     */
    private LocalDateTime nextReviewDate;

    // ============================================================
    // Metadata
    // ============================================================

    /**
     * Reviewed by
     */
    private String reviewedBy;

    /**
     * Review date
     */
    private LocalDateTime reviewDate;

    /**
     * Review notes
     */
    private String reviewNotes;

    /**
     * Custom metadata
     */
    private Map<String, Object> metadata;

    // ============================================================
    // Nested Classes
    // ============================================================

    /**
     * Compliance violation
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ComplianceViolation {
        private String violationId;
        private ViolationSeverity severity;
        private String rule;
        private String description;
        private String affectedField;
        private String remediation;
        private LocalDateTime detectedAt;
        private Boolean resolved;
        private LocalDateTime resolvedAt;
        private String resolvedBy;
    }

    /**
     * Policy check
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class PolicyCheck {
        private String checkId;
        private String policyName;
        private String description;
        private Boolean passed;
        private String result;
        private String expectedValue;
        private String actualValue;
        private ViolationSeverity severity;
    }

    /**
     * Remediation action
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class RemediationAction {
        private String actionId;
        private String title;
        private String description;
        private ViolationSeverity priority;
        private String status;
        private LocalDateTime dueDate;
        private String assignedTo;
    }

    // ============================================================
    // Helper Methods
    // ============================================================

    /**
     * Check if compliant
     */
    public boolean isCompliant() {
        return status == ComplianceStatus.COMPLIANT;
    }

    /**
     * Check if has violations
     */
    public boolean hasViolations() {
        return totalViolations != null && totalViolations > 0;
    }

    /**
     * Check if has critical violations
     */
    public boolean hasCriticalViolations() {
        return criticalViolations != null && criticalViolations > 0;
    }

    /**
     * Calculate compliance score
     */
    public void calculateComplianceScore() {
        if (totalChecks != null && totalChecks > 0) {
            double passRate = (passedChecks != null ? passedChecks : 0) * 100.0 / totalChecks;

            // Deduct points for violations
            double violationPenalty = 0;
            if (criticalViolations != null) violationPenalty += criticalViolations * 20;
            if (highViolations != null) violationPenalty += highViolations * 10;
            if (mediumViolations != null) violationPenalty += mediumViolations * 5;
            if (lowViolations != null) violationPenalty += lowViolations * 2;

            complianceScore = Math.max(0, passRate - violationPenalty);
        }
    }

    /**
     * Determine compliance status from score
     */
    public void determineStatus() {
        if (complianceScore == null) {
            status = ComplianceStatus.UNKNOWN;
        } else if (complianceScore >= 90) {
            status = ComplianceStatus.COMPLIANT;
        } else if (complianceScore >= 70) {
            status = ComplianceStatus.PARTIAL;
        } else {
            status = ComplianceStatus.NON_COMPLIANT;
        }
    }

    /**
     * Add violation
     */
    public void addViolation(ComplianceViolation violation) {
        if (violations == null) {
            violations = new java.util.ArrayList<>();
        }
        violations.add(violation);

        totalViolations = (totalViolations != null ? totalViolations : 0) + 1;

        switch (violation.getSeverity()) {
            case CRITICAL -> criticalViolations = (criticalViolations != null ? criticalViolations : 0) + 1;
            case HIGH -> highViolations = (highViolations != null ? highViolations : 0) + 1;
            case MEDIUM -> mediumViolations = (mediumViolations != null ? mediumViolations : 0) + 1;
            case LOW -> lowViolations = (lowViolations != null ? lowViolations : 0) + 1;
        }
    }

    /**
     * Add recommendation
     */
    public void addRecommendation(String recommendation) {
        if (recommendations == null) {
            recommendations = new java.util.ArrayList<>();
        }
        recommendations.add(recommendation);
    }

    /**
     * Add priority action
     */
    public void addPriorityAction(String action) {
        if (priorityActions == null) {
            priorityActions = new java.util.ArrayList<>();
        }
        priorityActions.add(action);
    }

    /**
     * Check if certification is valid
     */
    public boolean isCertificationValid() {
        if (!Boolean.TRUE.equals(certificationRequired)) {
            return true;
        }

        if (certificationDate == null) {
            return false;
        }

        if (certificationExpires != null && LocalDateTime.now().isAfter(certificationExpires)) {
            return false;
        }

        return true;
    }

    /**
     * Check if needs review
     */
    public boolean needsReview() {
        if (nextReviewDate != null && LocalDateTime.now().isAfter(nextReviewDate)) {
            return true;
        }

        if (hasCriticalViolations()) {
            return true;
        }

        return false;
    }

    /**
     * Get compliance grade
     */
    public String getComplianceGrade() {
        if (complianceScore == null) {
            return "N/A";
        }

        if (complianceScore >= 95) return "A+";
        if (complianceScore >= 90) return "A";
        if (complianceScore >= 85) return "B+";
        if (complianceScore >= 80) return "B";
        if (complianceScore >= 75) return "C+";
        if (complianceScore >= 70) return "C";
        if (complianceScore >= 65) return "D";
        return "F";
    }
}
